// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ZWoJR8jlqbvJL-FHdvBCMdJ45rlMHcY',
    appId: '1:124648803991:web:6ffcb833dcfa155ca8a3d2',
    messagingSenderId: '124648803991',
    projectId: 'donut-app-b0f98',
    authDomain: 'donut-app-b0f98.firebaseapp.com',
    storageBucket: 'donut-app-b0f98.firebasestorage.app',
    measurementId: 'G-9YG72F1VKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaEwBoHaWrZ6nRzZvu-TDJWzwPPm3SnBs',
    appId: '1:124648803991:android:99abf88ad6e9ffd8a8a3d2',
    messagingSenderId: '124648803991',
    projectId: 'donut-app-b0f98',
    storageBucket: 'donut-app-b0f98.firebasestorage.app',
  );
}
